/dev/random entropy fixes
HardenedBSD/hardenedBSD pull request #281
Opened 2017-09-21 18:12 UTC by badfilemagic

Fixes for entropy mixing in /dev/random:
* fixed issue that prevents RDRND and Via Padlock direct entropy sources from being mixed in.
* toss predictable/static fields from he_event structure to increase measurable entropy per SP800-90B

2017-09-21 18:15 UTC, lattera commented on sys/dev/random/fortuna.c
> +
Remove one of these extra blank lines.

2017-09-21 18:35 UTC, opntr commented on sys/dev/random/fortuna.c
> +	uint32_t entropy_data_size = 0;
Inline declaration in FreeBSD style are not permitted.

from other hand, this is why not size_t to reflect what it is?

2017-09-21 18:35 UTC, opntr commented on sys/dev/random/fortuna.c
> +	uint8_t entropy_data[entropy_data_size];
Same here, and VLAs are not really accepted too.

2017-09-21 18:35 UTC, opntr commented on sys/dev/random/random_harvestq.c
> +	 */
In this case would be better to put the removed code into #if 0 ... #endif block, to see whats happened

2017-09-21 18:37 UTC, lattera commented
I've posted a patch on top of his patch to clean things up a bit: http://ix.io/A4d

2017-09-21 18:38 UTC, opntr commented on sys/dev/random/fortuna.c
> +	else if (event->he_size == 8)
What's in else case, when the event->he_size if not 4 nor 8?
At least it would be nice to add an else panic() or at lease a KASSERT.

2017-09-21 18:56 UTC, lattera requested changes

2017-09-21 18:56 UTC, lattera commented on sys/dev/random/fortuna.c
> +	ssize_t entropy_data_size;
This should be at the top of the function.

2017-09-21 18:56 UTC, lattera commented on sys/dev/random/fortuna.c
> +	uint8_t entropy_data[entropy_data_size];
This should be at the top of the function.

2017-09-21 18:56 UTC, lattera commented on sys/dev/random/fortuna.c
> +	randomdev_hash_iterate(&fortuna_state.fs_pool[pl].fsp_hash, entropy_data, entropy_data_size);
Wrap to 70 characters, next line wrap indent + 4 spaces.

2017-09-21 18:56 UTC, lattera commented on sys/dev/random/random_harvestq.c
> +	 * Temporary fix until upstream includes full patch from jmg.
Wrap the lines at 70 characters. Use proper capitalization and punctuation.

2017-09-21 18:56 UTC, lattera commented on sys/dev/random/fortuna.c
> +	 * conducting SP800-90B entropy analysis measurements of seed material fed into PRNG
Wrap lines at 70 characters. Use proper capitalization and punctuation.

2017-09-25 01:39 UTC, badfilemagic commented
fa96ed6 should have all the changes. changes to fortuna.c are good. the stuff I merged into my fork from oliver's last patch from playground, I am still looking at. there's a bug somewhere I just haven't nailed it down yet.

2017-09-30 00:27 UTC, lattera commented on sys/dev/random/random_harvestq.c
> +	bool first;
One last nitpick: There should be a blank line between variable declarations and code.

2017-09-30 21:57 UTC, opntr commented
Cherry-picked the squashed patches with collaboration from wdf (@badfilemagic):

https://github.com/HardenedBSD/hardenedBSD/commit/8d809124d563937edd84c9c9d5494406e359c55c
https://github.com/HardenedBSD/hardenedBSD/commit/0054e3e170e083811acc9f3b637f8be8a86c03e7

2017-09-30 21:57 UTC, closed without merging